name: Convert CSV to HTML

on:
  push:
    paths:
      - shiga_menu.csv
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2

      - name: Pythonをセットアップ
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 依存関係をインストール
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: CSVをHTMLに変換
        run: python csv_to_html.py

      - name: 生成されたHTMLをコミット
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add index.html
          git commit -m "Update index.html from shiga_menu.csv"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
